### ISSUE TITLE
Regions still active in storage file but they dissapear in game. 

### ISSUE THREAD

**Issue by Levaithon** [Aquerr/WorldRebuilder#4]
If i make a region with worldrebuilder it works and i can do what i want to do. But when i restart my server and then type the command /wr list then my region is gone. Also it is not working in game. But when i go to the storage file in the config the region is still there. 

I dont know how to fix this.

**Comment by Aquerr** [comment]
Do you get any error logs related to WorldRebuilder in the console while starting your server?
