### ISSUE TITLE
Active regions not allowing players to drop items

### ISSUE THREAD

**Issue by aqua-air** [Aquerr/WorldRebuilder#5]
I used this to make a regenerating arena, but only while the rebuilder region was active, none of my players are dropping items on death. All their items on death are being cleared, and nothing dropped. Only happens with the region active. I loved having a rebuilder but this isn't compatible with any use for an arena, because players need the items they won from the fight!!

**Comment by Aquerr** [comment]
Hey! Thanks for opening the issue. 
I have few questions:
1. What version of the plugin you are using?
2. What is the version of Forge and Sponge?
3. Have you tried switching the drop_blocks flag in the region?

**Comment by aqua-air** [comment]
WorldRebuilder-1.3.0.jar
Forge 14.23.5.2860
MC 1.12.2
spongeforge-1.12.2-2838-7.4.7.jar

**Comment by Aquerr** [comment]
Fixed in latest release for 1.12.2. I am closing this issue.
